/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { School } from "./School";
import { SchoolCountArgs } from "./SchoolCountArgs";
import { SchoolFindManyArgs } from "./SchoolFindManyArgs";
import { SchoolFindUniqueArgs } from "./SchoolFindUniqueArgs";
import { CreateSchoolArgs } from "./CreateSchoolArgs";
import { UpdateSchoolArgs } from "./UpdateSchoolArgs";
import { DeleteSchoolArgs } from "./DeleteSchoolArgs";
import { AcademicYearFindManyArgs } from "../../academicYear/base/AcademicYearFindManyArgs";
import { AcademicYear } from "../../academicYear/base/AcademicYear";
import { UserFindManyArgs } from "../../user/base/UserFindManyArgs";
import { User } from "../../user/base/User";
import { SchoolService } from "../school.service";
@graphql.Resolver(() => School)
export class SchoolResolverBase {
  constructor(protected readonly service: SchoolService) {}

  async _schoolsMeta(
    @graphql.Args() args: SchoolCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [School])
  async schools(@graphql.Args() args: SchoolFindManyArgs): Promise<School[]> {
    return this.service.schools(args);
  }

  @graphql.Query(() => School, { nullable: true })
  async school(
    @graphql.Args() args: SchoolFindUniqueArgs
  ): Promise<School | null> {
    const result = await this.service.school(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => School)
  async createSchool(@graphql.Args() args: CreateSchoolArgs): Promise<School> {
    return await this.service.createSchool({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => School)
  async updateSchool(
    @graphql.Args() args: UpdateSchoolArgs
  ): Promise<School | null> {
    try {
      return await this.service.updateSchool({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => School)
  async deleteSchool(
    @graphql.Args() args: DeleteSchoolArgs
  ): Promise<School | null> {
    try {
      return await this.service.deleteSchool(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [AcademicYear], { name: "academicYears" })
  async findAcademicYears(
    @graphql.Parent() parent: School,
    @graphql.Args() args: AcademicYearFindManyArgs
  ): Promise<AcademicYear[]> {
    const results = await this.service.findAcademicYears(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [User], { name: "users" })
  async findUsers(
    @graphql.Parent() parent: School,
    @graphql.Args() args: UserFindManyArgs
  ): Promise<User[]> {
    const results = await this.service.findUsers(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
