/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AcademicYearService } from "../academicYear.service";
import { AcademicYearCreateInput } from "./AcademicYearCreateInput";
import { AcademicYear } from "./AcademicYear";
import { AcademicYearFindManyArgs } from "./AcademicYearFindManyArgs";
import { AcademicYearWhereUniqueInput } from "./AcademicYearWhereUniqueInput";
import { AcademicYearUpdateInput } from "./AcademicYearUpdateInput";
import { TermFindManyArgs } from "../../term/base/TermFindManyArgs";
import { Term } from "../../term/base/Term";
import { TermWhereUniqueInput } from "../../term/base/TermWhereUniqueInput";

export class AcademicYearControllerBase {
  constructor(protected readonly service: AcademicYearService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AcademicYear })
  async createAcademicYear(
    @common.Body() data: AcademicYearCreateInput
  ): Promise<AcademicYear> {
    return await this.service.createAcademicYear({
      data: {
        ...data,

        school: data.school
          ? {
              connect: data.school,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        school: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        year: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [AcademicYear] })
  @ApiNestedQuery(AcademicYearFindManyArgs)
  async academicYears(@common.Req() request: Request): Promise<AcademicYear[]> {
    const args = plainToClass(AcademicYearFindManyArgs, request.query);
    return this.service.academicYears({
      ...args,
      select: {
        createdAt: true,
        id: true,

        school: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        year: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AcademicYear })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async academicYear(
    @common.Param() params: AcademicYearWhereUniqueInput
  ): Promise<AcademicYear | null> {
    const result = await this.service.academicYear({
      where: params,
      select: {
        createdAt: true,
        id: true,

        school: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        year: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AcademicYear })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateAcademicYear(
    @common.Param() params: AcademicYearWhereUniqueInput,
    @common.Body() data: AcademicYearUpdateInput
  ): Promise<AcademicYear | null> {
    try {
      return await this.service.updateAcademicYear({
        where: params,
        data: {
          ...data,

          school: data.school
            ? {
                connect: data.school,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          school: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          year: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AcademicYear })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteAcademicYear(
    @common.Param() params: AcademicYearWhereUniqueInput
  ): Promise<AcademicYear | null> {
    try {
      return await this.service.deleteAcademicYear({
        where: params,
        select: {
          createdAt: true,
          id: true,

          school: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          year: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/terms")
  @ApiNestedQuery(TermFindManyArgs)
  async findTerms(
    @common.Req() request: Request,
    @common.Param() params: AcademicYearWhereUniqueInput
  ): Promise<Term[]> {
    const query = plainToClass(TermFindManyArgs, request.query);
    const results = await this.service.findTerms(params.id, {
      ...query,
      select: {
        academicYear: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/terms")
  async connectTerms(
    @common.Param() params: AcademicYearWhereUniqueInput,
    @common.Body() body: TermWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      terms: {
        connect: body,
      },
    };
    await this.service.updateAcademicYear({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/terms")
  async updateTerms(
    @common.Param() params: AcademicYearWhereUniqueInput,
    @common.Body() body: TermWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      terms: {
        set: body,
      },
    };
    await this.service.updateAcademicYear({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/terms")
  async disconnectTerms(
    @common.Param() params: AcademicYearWhereUniqueInput,
    @common.Body() body: TermWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      terms: {
        disconnect: body,
      },
    };
    await this.service.updateAcademicYear({
      where: params,
      data,
      select: { id: true },
    });
  }
}
