/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CalendarService } from "../calendar.service";
import { CalendarCreateInput } from "./CalendarCreateInput";
import { Calendar } from "./Calendar";
import { CalendarFindManyArgs } from "./CalendarFindManyArgs";
import { CalendarWhereUniqueInput } from "./CalendarWhereUniqueInput";
import { CalendarUpdateInput } from "./CalendarUpdateInput";
import { EventFindManyArgs } from "../../event/base/EventFindManyArgs";
import { Event } from "../../event/base/Event";
import { EventWhereUniqueInput } from "../../event/base/EventWhereUniqueInput";
import { HolidayFindManyArgs } from "../../holiday/base/HolidayFindManyArgs";
import { Holiday } from "../../holiday/base/Holiday";
import { HolidayWhereUniqueInput } from "../../holiday/base/HolidayWhereUniqueInput";

export class CalendarControllerBase {
  constructor(protected readonly service: CalendarService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Calendar })
  async createCalendar(
    @common.Body() data: CalendarCreateInput
  ): Promise<Calendar> {
    return await this.service.createCalendar({
      data: {
        ...data,

        event: data.event
          ? {
              connect: data.event,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        date: true,

        event: {
          select: {
            id: true,
          },
        },

        id: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Calendar] })
  @ApiNestedQuery(CalendarFindManyArgs)
  async calendars(@common.Req() request: Request): Promise<Calendar[]> {
    const args = plainToClass(CalendarFindManyArgs, request.query);
    return this.service.calendars({
      ...args,
      select: {
        createdAt: true,
        date: true,

        event: {
          select: {
            id: true,
          },
        },

        id: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Calendar })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async calendar(
    @common.Param() params: CalendarWhereUniqueInput
  ): Promise<Calendar | null> {
    const result = await this.service.calendar({
      where: params,
      select: {
        createdAt: true,
        date: true,

        event: {
          select: {
            id: true,
          },
        },

        id: true,
        typeField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Calendar })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCalendar(
    @common.Param() params: CalendarWhereUniqueInput,
    @common.Body() data: CalendarUpdateInput
  ): Promise<Calendar | null> {
    try {
      return await this.service.updateCalendar({
        where: params,
        data: {
          ...data,

          event: data.event
            ? {
                connect: data.event,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          date: true,

          event: {
            select: {
              id: true,
            },
          },

          id: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Calendar })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCalendar(
    @common.Param() params: CalendarWhereUniqueInput
  ): Promise<Calendar | null> {
    try {
      return await this.service.deleteCalendar({
        where: params,
        select: {
          createdAt: true,
          date: true,

          event: {
            select: {
              id: true,
            },
          },

          id: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/events")
  @ApiNestedQuery(EventFindManyArgs)
  async findEvents(
    @common.Req() request: Request,
    @common.Param() params: CalendarWhereUniqueInput
  ): Promise<Event[]> {
    const query = plainToClass(EventFindManyArgs, request.query);
    const results = await this.service.findEvents(params.id, {
      ...query,
      select: {
        calendar: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        endTime: true,
        id: true,
        location: true,
        startTime: true,
        title: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/events")
  async connectEvents(
    @common.Param() params: CalendarWhereUniqueInput,
    @common.Body() body: EventWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      events: {
        connect: body,
      },
    };
    await this.service.updateCalendar({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/events")
  async updateEvents(
    @common.Param() params: CalendarWhereUniqueInput,
    @common.Body() body: EventWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      events: {
        set: body,
      },
    };
    await this.service.updateCalendar({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/events")
  async disconnectEvents(
    @common.Param() params: CalendarWhereUniqueInput,
    @common.Body() body: EventWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      events: {
        disconnect: body,
      },
    };
    await this.service.updateCalendar({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/holidays")
  @ApiNestedQuery(HolidayFindManyArgs)
  async findHolidays(
    @common.Req() request: Request,
    @common.Param() params: CalendarWhereUniqueInput
  ): Promise<Holiday[]> {
    const query = plainToClass(HolidayFindManyArgs, request.query);
    const results = await this.service.findHolidays(params.id, {
      ...query,
      select: {
        calendar: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        date: true,
        description: true,
        id: true,
        title: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/holidays")
  async connectHolidays(
    @common.Param() params: CalendarWhereUniqueInput,
    @common.Body() body: HolidayWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      holidays: {
        connect: body,
      },
    };
    await this.service.updateCalendar({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/holidays")
  async updateHolidays(
    @common.Param() params: CalendarWhereUniqueInput,
    @common.Body() body: HolidayWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      holidays: {
        set: body,
      },
    };
    await this.service.updateCalendar({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/holidays")
  async disconnectHolidays(
    @common.Param() params: CalendarWhereUniqueInput,
    @common.Body() body: HolidayWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      holidays: {
        disconnect: body,
      },
    };
    await this.service.updateCalendar({
      where: params,
      data,
      select: { id: true },
    });
  }
}
